# typed: false
# frozen_string_literal: true
# This file was generated by go-xbuild-go v1.0.9. DO NOT EDIT
# https://github.com/muquit/go-xbuild-go
class MarkdownServe < Formula
  desc ""
  homepage "https://github.com/muquit/markdown-serve"
  version "1.0.1"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/muquit/markdown-serve/releases/download/v1.0.1/markdown-serve-v1.0.1-darwin-arm64.d.tar.gz"
    sha256 "3f91053e580ab8eb0077ce4b6ca8f3787f7db7b02ab58bae8d70c51173d91499"
  elsif OS.mac? && Hardware::CPU.intel?
    url "https://github.com/muquit/markdown-serve/releases/download/v1.0.1/markdown-serve-v1.0.1-darwin-amd64.d.tar.gz"
    sha256 "ec69fb3a4c3075f9aa3e9717254b9393a113272a912cb664191c64774e190c32"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/muquit/markdown-serve/releases/download/v1.0.1/markdown-serve-v1.0.1-linux-amd64.d.tar.gz"
    sha256 "2be0cba942b744cc75663854cc76f3e911a87158da91a8b92ee58d4fc14b869c"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/muquit/markdown-serve/releases/download/v1.0.1/markdown-serve-v1.0.1-linux-arm64.d.tar.gz"
    sha256 "1a162d0d9ab15bb1de60b945c765fb5e1f4a43badfaa787e84ef2fdbbcf8556a"
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "markdown-serve-v#{version}-darwin-arm64" => "markdown-serve"
      else
        bin.install "markdown-serve-v#{version}-darwin-amd64" => "markdown-serve"
      end
    elsif OS.linux?
      if Hardware::CPU.arm?
        bin.install "markdown-serve-v#{version}-linux-arm64" => "markdown-serve"
      else
        bin.install "markdown-serve-v#{version}-linux-amd64" => "markdown-serve"
      end
    end
  end
end
