# typed: false
# frozen_string_literal: true
# This file was generated by go-xbuild-go v1.0.9. DO NOT EDIT
# https://github.com/muquit/go-xbuild-go
class MarkdownServe < Formula
  desc ""
  homepage "https://github.com/muquit/markdown-serve"
  version "1.0.1"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/muquit/markdown-serve/releases/download/v1.0.1/markdown-serve-v1.0.1-darwin-arm64.d.tar.gz"
    sha256 "b02a0774fbe2deeb4fac79666579561c8afc2b62509310177d2b1552a91f5659"
  elsif OS.mac? && Hardware::CPU.intel?
    url "https://github.com/muquit/markdown-serve/releases/download/v1.0.1/markdown-serve-v1.0.1-darwin-amd64.d.tar.gz"
    sha256 "285009e429ed19a9a00e01682a90e439a070db9147ecf06f5fb13f31fc8ed262"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/muquit/markdown-serve/releases/download/v1.0.1/markdown-serve-v1.0.1-linux-amd64.d.tar.gz"
    sha256 "21c3a14634ee2755b71fdf731961c4eb3013792247d1b4173ef12cc11cc16d3c"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/muquit/markdown-serve/releases/download/v1.0.1/markdown-serve-v1.0.1-linux-arm64.d.tar.gz"
    sha256 "c1610768a0b74896a220dc22eb73a02674fd9b132a4bbd32373097e7e5ecab86"
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "markdown-serve-v#{version}-darwin-arm64" => "markdown-serve"
      else
        bin.install "markdown-serve-v#{version}-darwin-amd64" => "markdown-serve"
      end
    elsif OS.linux?
      if Hardware::CPU.arm?
        bin.install "markdown-serve-v#{version}-linux-arm64" => "markdown-serve"
      else
        bin.install "markdown-serve-v#{version}-linux-amd64" => "markdown-serve"
      end
    end
  end
end
