# typed: false
# frozen_string_literal: true
# This file was generated by go-xbuild-go v1.0.9. DO NOT EDIT
# https://github.com/muquit/go-xbuild-go
class MarkdownServe < Formula
  desc ""
  homepage "https://github.com/muquit/markdown-serve"
  version "1.0.1"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/muquit/markdown-serve/releases/download/v1.0.1/markdown-serve-v1.0.1-darwin-arm64.d.tar.gz"
    sha256 "b6e0e3f55ab1bf1bbb468e89aff48113352307e383e1a05877b3a3c770e7a0f0"
  elsif OS.mac? && Hardware::CPU.intel?
    url "https://github.com/muquit/markdown-serve/releases/download/v1.0.1/markdown-serve-v1.0.1-darwin-amd64.d.tar.gz"
    sha256 "a5a070f1eb20b4d665f2844e6459e8b51d9d60fd44038ad5dea1a99655f937a1"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/muquit/markdown-serve/releases/download/v1.0.1/markdown-serve-v1.0.1-linux-amd64.d.tar.gz"
    sha256 "32f9885d94b47e518696df8f28999e240fba13e46b2a2bda900a000bf4d67422"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/muquit/markdown-serve/releases/download/v1.0.1/markdown-serve-v1.0.1-linux-arm64.d.tar.gz"
    sha256 "d36feb7e3375dc13573850c94114bdcf095e118e39d87689c99e9281882d3800"
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "markdown-serve-v#{version}-darwin-arm64" => "markdown-serve"
      else
        bin.install "markdown-serve-v#{version}-darwin-amd64" => "markdown-serve"
      end
    elsif OS.linux?
      if Hardware::CPU.arm?
        bin.install "markdown-serve-v#{version}-linux-arm64" => "markdown-serve"
      else
        bin.install "markdown-serve-v#{version}-linux-amd64" => "markdown-serve"
      end
    end
  end
end
